cargo-features = ["edition"]

[package]
name = "embrio-native"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[dependencies]
embrio-core = { path = "../embrio-core" }

[dependencies.futures-core-preview]
version = "0.3.0-alpha.5"
default-features = false
