[package]
name = "embrio-async"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[dependencies]
embrio-async-dehygiene = { path = "dehygiene" }
futures-core-preview = { version = "0.3.0-alpha.13", default-features = false }

[dev-dependencies]
futures-preview = "0.3.0-alpha.13"
pin-utils = "0.1.0-alpha.4"
